### ISSUE TITLE
TTS doesn't work 

### ISSUE THREAD

**Issue by awaterman1967** [toggledbits/Sonos-Vera#1]
Thx for 2.0 !

With:
"
luup.call_action("urn:micasaverde-com:serviceId:Sonos1", "Say",
                 {Text="The sun shines outside", Language="en"},
                 120)
"
in my scene, only only the Sonos_chime goes off. The text are not spoken to my Sonos.

Engine: is RV

Help!

**Comment by guerinwoodgate** [comment]
Same for me using RV.  Something else that is noteworthy is the chime is set to default and the system only chimes for RV.

**Comment by awaterman1967** [comment]
I understood that RV TTS no longer works. Thanks to Patrick!, I now have my Vera TTS working with Azure. However, I understood that Azure does not (yet) work with Dutch language.

**Comment by toggledbits** [comment]
Azure works in Dutch, it's just missing from the plugin's list. But you can make it use any voice you want, you are not limited to what is on the list. Where you choose the language, just make the "custom" selection, and then enter `nl-NL-HannaRUS` in the text box next to the dropdown. That should get you some fine Dutch speech audio. 

Ref: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support
